const string PREFIX_COMMIT = "\033[35;1m[SupraCommit]\033[0m: ";

[CCode (cname = "system", cheader_filename = "stdlib.h")]
public extern void system (string command);

// supracommit est un logiciel qui permet de donner des commits a ses diff de git

string tell_IA_diff (string prompt) throws Error {

	var gemini = new Gemini(ParseOption.MODEL, ParseOption.API_KEY);
	var msg = gemini.send(prompt);

	var content = "\n" + msg.content;
	return content;
}

public void main (string []av) {
	Intl.setlocale ();

	try {


		var options = new ParseOption();
		options.parse (av);

		string output;
		string errput;

		Process.spawn_command_line_sync("git rev-parse --show-toplevel", out output, out errput);
		var repo_path = output._strip();
		Process.spawn_command_line_sync("git diff --cached", out output, out errput); 

		if (output._strip() == "") {
			print ("git add some files before using supraCommit\n");
			return;
		}

		var prompt = Format.get_prompt(repo_path, output);
		var content = tell_IA_diff(prompt);
		var commits = content.split ("\n- ");

		if (commits.length == 0) {
			print (PREFIX_COMMIT + ": No commit message generated by the AI.\n");
			return;
		}
		var commit = commits[0]._strip();
		print (PREFIX_COMMIT + "Voici le commit proposé par l'IA:\n\n");
		print ("- %s\n\n", commit);
		print (PREFIX_COMMIT + "Accepter le commit suivants ? (y/n): ");
		var is_yes = stdin.read_line();

		if ("y" in is_yes._strip().down()) {
			Process.spawn_command_line_sync("git commit -m \"%s\"".printf(commit), out output, out errput);
			print (PREFIX_COMMIT + "Commit effectué avec succès.\n");
		} else {
			print (PREFIX_COMMIT + "Commit annulé par l'utilisateur.\n");
		}

	}
	catch (Error e) {
		printerr (PREFIX_COMMIT + "An error occurred: %s\n", e.message);
	}
}
