public errordomain SupraCommitError {
	API_ERROR,
	GIT_ERROR
}

/**
 * Call the API to get a commit message suggestion based on the staged changes, 
 * @param prompt The prompt to send to the AI, containing the diff and context.
 * @return The content of the AI's response, which should include the suggested commit message.
 * @throws Error If there is an issue with the API call or response processing.
 */
private string tell_IA_diff (string prompt) throws Error {
	var gemini = new Gemini(ParseOption.MODEL, ParseOption.API_KEY);
	var msg = gemini.send(prompt);

	var content = "\n" + msg.content;
	return content;
}

/**
 * Executes the git commit command with the provided message.
 * @param message The commit message to use for the git commit.
 * @throws Error If there is an issue executing the git command.
 */
private void run_git_commit (string message) throws Error {
	string msg = "git commit -m " + Shell.quote(message);
	string output;
	string errput;
	int status;

	Process.spawn_command_line_sync(msg, out output, out errput, out status);

	if (status == 0)
		print (PREFIX_COMMIT + " \033[1;32mDone!\033[0m Changes committed successfully.\n");
	else
		throw new SupraCommitError.GIT_ERROR("Git: %s", errput);
}

/**
 * Retrieves the git diff of staged changes and the repository path.
 * @param repo_path An output parameter that will contain the path to the git repository.
 * @return The git diff of staged changes as a string.
 * @throws Error If there is an issue executing the git commands.
 */
private string get_git_diff (out string repo_path) throws Error {
	string output;
	string errput;
	int status;

	Process.spawn_command_line_sync("git rev-parse --show-toplevel", out output, out errput, out status);
	if (status != 0)
		throw new SupraCommitError.GIT_ERROR("Git: %s", errput);
	repo_path = output._strip();
	Process.spawn_command_line_sync("git diff --cached", out output, out errput, out status);
	if (status != 0)
		throw new SupraCommitError.GIT_ERROR("Git: %s", errput);
	output._strip();
	return (owned)output;
}

/**
 * Main function to run the supraCommit process. It checks for staged changes, generates a commit message using the AI, and prompts the user to accept or reject the suggestion.
 * @throws Error If there is an issue with git commands or AI processing.
 */
public void run_supracommit () throws Error {
	string repo_path;
	string git_diff = get_git_diff(out repo_path);

	if (git_diff == "") {
		print (PREFIX_COMMIT + "git add some files before using supraCommit\n");
		return;
	}

	var prompt = Format.get_prompt(repo_path, git_diff);
	var content = tell_IA_diff(prompt);

	var commits = content.split ("\n- ");
	if (commits.length == 0) {
		print (PREFIX_COMMIT + "No commit message generated by the AI.\n");
		return;
	}
	var commit = commits[0]._strip();
	print (PREFIX_COMMIT + " \033[1mProposed commit message:\033[0m\n");
	print ("  \033[32m→\033[0m %s\n\n", commit);
	print (PREFIX_COMMIT + "Accept this suggestion? [y/N]: ");

	var is_yes = stdin.read_line();
	if ("y" in is_yes._strip().down()) {
		run_git_commit (commit);
	} else {
		print (PREFIX_COMMIT + "Commit aborted. (Change discarded)\n");
	}
}

