/**
 * Call the API to get a commit message suggestion based on the staged changes, 
 * @param prompt The prompt to send to the AI, containing the diff and context.
 * @return The content of the AI's response, which should include the suggested commit message.
 * @throws Error If there is an issue with the API call or response processing.
 */
private string call_ia () throws Error {
	var prompt = Format.get_prompt();
	var ia = Brain.create(ParseOption.MODEL, ParseOption.API_KEY);
	var msg = ia.send(prompt);

	return ("\n" + msg.content);
}

/**
 * Main function to run the supraCommit process. It checks for staged changes, generates a commit message using the AI, and prompts the user to accept or reject the suggestion.
 * @throws Error If there is an issue with git commands or AI processing.
 */
public void run_supracommit () throws Error {
	var content = call_ia();

	var commits = content.split("\n- ");
	if (commits.length == 0) {
		print (PREFIX_COMMIT + "No commit message generated by the AI.\n");
		return;
	}

	var commit = commits[0]._strip();
	if (ParseOption.skip_ci) {
		commit += " [skip ci]";
	}

	print(PREFIX_COMMIT + " \033[1mProposed commit message:\033[0m\n");
	print("  \033[32m→\033[0m %s\n\n", commit);
	print(PREFIX_COMMIT + "Accept this suggestion? [y/N]: ");

	string is_yes = stdin.read_line();
	if ("y" in is_yes._strip().down()) {
		Git.commit(commit);
	} else {
		print(PREFIX_COMMIT + "Commit aborted. (Change discarded)\n");
	}
}
